// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadVault(vaultPath: string) : Promise<Result<LoadVaultResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_vault", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFiles(vaultPath: string) : Promise<Result<TreeItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_files", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readNote(vaultPath: string, noteId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_note", { vaultPath, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeNote(vaultPath: string, noteId: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_note", { vaultPath, noteId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNoteMetadata(vaultPath: string, noteId: string) : Promise<Result<NoteMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note_metadata", { vaultPath, noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags(vaultPath: string) : Promise<Result<TagEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchNotes(vaultPath: string, query: string) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { vaultPath, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLinkGraph(vaultPath: string) : Promise<Result<LinkGraph, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_link_graph", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensureBundle(vaultPath: string, path: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_bundle", { vaultPath, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNote(vaultPath: string, parentPath: string, name: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { vaultPath, parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLayer(notePath: string, kind: string) : Promise<Result<LayerResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_layer", { notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCanvas(vaultPath: string, parentPath: string, name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_canvas", { vaultPath, parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async attachCanvasToNote(vaultPath: string, canvasPath: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_canvas_to_note", { vaultPath, canvasPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkLayer(vaultPath: string, notePath: string, kind: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_layer", { vaultPath, notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLayer(vaultPath: string, notePath: string, kind: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_layer", { vaultPath, notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteLayers(notePath: string) : Promise<Result<NoteLayers, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_layers", { notePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveItem(vaultPath: string, sourcePath: string, targetPath: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_item", { vaultPath, sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameItem(vaultPath: string, path: string, newName: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_item", { vaultPath, path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteItem(vaultPath: string, path: string) : Promise<Result<FsMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_item", { vaultPath, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileMetadata(path: string) : Promise<Result<FileMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openVault() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInExplorer(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAsset(vaultPath: string, notePath: string, sourcePath: string) : Promise<Result<ImportedAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset", { vaultPath, notePath, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAssetBytes(vaultPath: string, notePath: string, bytes: number[], suggestedExt: string) : Promise<Result<ImportedAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset_bytes", { vaultPath, notePath, bytes, suggestedExt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickAssetFile(imagesOnly: boolean) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_asset_file", { imagesOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save arbitrary text to a user-chosen location via the native save dialog.
 * The destination is picked here (never supplied by the webview), so there is
 * no arbitrary-write-from-JS vector — used for exporting presets.
 */
async exportTextFile(contents: string, defaultName: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_text_file", { contents, defaultName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a user-chosen text file via the native dialog and return its contents.
 * The path is chosen here, so the webview can't read arbitrary files — used
 * for importing presets (which live outside the vault).
 */
async importTextFile() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_text_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type FileMetadata = { created: number | null; modified: number | null; word_count: number }
export type FsMutationResult = { primaryId: string | null; primaryPath: string | null; pathChanges: PathChange[]; deletedPaths: string[]; deletedIds: string[] }
export type ImportedAsset = { relPath: string; absPath: string; fileName: string; kind: string }
export type IndexedNote = { id: string; path: string; title: string; modified: number | null; wordCount: number }
export type LayerResult = { notePath: string; layerPath: string; kind: string; pathChanges: PathChange[] }
export type LinkGraph = { nodes: LinkGraphNode[]; edges: LinkGraphEdge[] }
export type LinkGraphEdge = { source: string; target: string; label: string; unresolved?: boolean | null }
export type LinkGraphNode = { id: string; label: string; unresolved?: boolean | null }
export type LoadVaultResult = { tree: TreeItem[]; notes: IndexedNote[]; sync: SyncReport }
export type NoteLayers = { canvas: boolean; sketch: boolean; database: boolean }
export type NoteMetadata = { created: number | null; modified: number | null; wordCount: number }
export type PathChange = { oldPath: string; newPath: string }
export type SearchResult = { note: IndexedNote; matchType: string; snippet: string | null; score: number }
export type SyncReport = { inserted: number; updated: number; deleted: number; warnings: string[]; pathToId: Partial<{ [key in string]: string }> }
export type TagEntry = { tag: string; notes: IndexedNote[] }
export type TreeItem = { id: string; path: string; name: string; type: string; icon: string; children?: TreeItem[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
