// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadVault(vaultPath: string) : Promise<Result<LoadVaultResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_vault", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the vault that another window has already activated without replacing
 * the process-wide backend context a second time.
 */
async loadActiveVault() : Promise<Result<LoadVaultResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_active_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async preflightVault(vaultPath: string) : Promise<Result<VaultPreflight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preflight_vault", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyIdMigration(vaultPath: string) : Promise<Result<IdMigrationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_id_migration", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectIdMigrations(vaultPath: string) : Promise<Result<IdMigrationRecovery[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_id_migrations", { vaultPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recoverIdMigration(vaultPath: string, journalPath: string, action: IdMigrationRecoveryAction) : Promise<Result<IdMigrationRecovery, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_id_migration", { vaultPath, journalPath, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFiles() : Promise<Result<TreeItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConflictCopy(path: string, content: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_conflict_copy", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots(sourcePath: string) : Promise<Result<SnapshotEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryStats() : Promise<Result<HistoryStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewHistoryCleanup(retention: HistoryRetention) : Promise<Result<HistoryCleanupPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_history_cleanup", { retention }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupHistory(retention: HistoryRetention) : Promise<Result<HistoryCleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_history", { retention }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(snapshotId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readSnapshotText(snapshotId: string) : Promise<Result<SnapshotText, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_snapshot_text", { snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRecovery(id: string, documentKind: string, pathHint: string, content: string) : Promise<Result<RecoveryEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recovery", { id, documentKind, pathHint, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readRecovery(id: string) : Promise<Result<RecoveryEntry | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_recovery", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRecovery(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_recovery", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecovery() : Promise<Result<RecoveryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recovery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTrash() : Promise<Result<TrashEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreTrash(trashId: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_trash", { trashId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeTrash(trashId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_trash", { trashId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readNote(noteId: string) : Promise<Result<NoteReadOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_note", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeNote(request: WriteNoteRequest) : Promise<Result<WriteNoteOutcome, WriteNoteError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_note", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreDeletedNote(request: RestoreDeletedNoteRequest) : Promise<Result<WriteNoteOutcome, WriteNoteError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_deleted_note", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNoteMetadata(noteId: string) : Promise<Result<NoteMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note_metadata", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNoteProperties(noteId: string) : Promise<Result<NoteProperties, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note_properties", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertCustomProperty(noteId: string, property: CustomProperty) : Promise<Result<CustomProperty, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_custom_property", { noteId, property }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomProperty(noteId: string, propertyId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_property", { noteId, propertyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags() : Promise<Result<TagEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchNotes(query: string) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLinkGraph() : Promise<Result<LinkGraph, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_link_graph") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensureBundle(path: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNote(parentPath: string, name: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLayer(notePath: string, kind: string) : Promise<Result<LayerResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_layer", { notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCanvas(parentPath: string, name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_canvas", { parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async attachCanvasToNote(canvasPath: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_canvas_to_note", { canvasPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkLayer(notePath: string, kind: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_layer", { notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLayer(notePath: string, kind: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_layer", { notePath, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteLayers(notePath: string) : Promise<Result<NoteLayers, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_layers", { notePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveItem(sourcePath: string, targetPath: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_item", { sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewMoveRefactor(sourcePath: string, targetPath: string) : Promise<Result<RefactorPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_move_refactor", { sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameItem(path: string, newName: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_item", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewRenameRefactor(path: string, newName: string) : Promise<Result<RefactorPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_rename_refactor", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteItem(path: string) : Promise<Result<MutationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_item", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileMetadata(path: string) : Promise<Result<FileMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openVault() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startVaultWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_vault_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopVaultWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_vault_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInExplorer(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAsset(notePath: string, sourcePath: string) : Promise<Result<ImportedAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset", { notePath, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAssetBytes(notePath: string, bytes: number[], suggestedExt: string) : Promise<Result<ImportedAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset_bytes", { notePath, bytes, suggestedExt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickAssetFile(imagesOnly: boolean) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_asset_file", { imagesOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportTextFile(contents: string, defaultName: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_text_file", { contents, defaultName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importTextFile() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_text_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readAppData(rel: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_app_data", { rel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeAppData(rel: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_app_data", { rel, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readVaultMeta(rel: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_vault_meta", { rel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeVaultMeta(rel: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_vault_meta", { rel, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteVaultMeta(rel: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_vault_meta", { rel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeAiCredential(credentialId: string, secret: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_ai_credential", { credentialId, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAiCredential(credentialId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_ai_credential", { credentialId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectAiCredential(credentialId: string) : Promise<Result<CredentialInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_ai_credential", { credentialId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAiRequest(streamId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_ai_request", { streamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiChat(config: AiConfig, messages: AiMessage[], system: string | null, streamId: string | null) : Promise<Result<string, AiChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_chat", { config, messages, system, streamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiChatError = { code: AiErrorCode; provider: string }
export type AiConfig = { 
/**
 * Wire family: "ollama" | "openai" | "anthropic" | "azure".
 */
provider: string; model: string; 
/**
 * Empty string falls back to the family's default endpoint.
 */
baseUrl: string; credentialId: string | null; apiKey: string | null; maxTokens: number | null; 
/**
 * Azure only: API version query param.
 */
apiVersion: string | null }
/**
 * Safe error shape exposed to the renderer. Provider responses and request
 * details may contain endpoints or credentials, so they never cross IPC.
 */
export type AiErrorCode = "cancelled" | "missingCredential" | "invalidConfiguration" | "providerRejected" | "invalidResponse" | "network" | "requestFailed"
export type AiMessage = { 
/**
 * "user" | "assistant"
 */
role: string; content: string }
export type CredentialInfo = { exists: boolean; masked: string | null }
export type CustomProperty = { id: string; name: string; icon: string; propertyType: string; value: string; settings: string }
export type FileMetadata = { created: number | null; modified: number | null; word_count: number }
/**
 * Read-only view of a single YAML frontmatter entry. The original YAML stays
 * on disk untouched; `value` is only a display representation for the UI.
 */
export type FrontmatterProperty = { key: string; value: string; valueKind: string }
export type FrontmatterStatus = "none" | "valid" | "invalid" | "unterminated"
export type FsMutationResult = { primaryId: string | null; primaryPath: string | null; pathChanges: PathChange[]; deletedPaths: string[]; deletedIds: string[] }
export type HistoryCleanupPreview = { removedCount: number; freedBytes: number; remaining: HistoryStats }
export type HistoryCleanupResult = { removedCount: number; freedBytes: number; remaining: HistoryStats }
export type HistoryRetention = { maxSnapshotsPerNote: number; maxAgeDays: number | null }
export type HistoryStats = { snapshotCount: number; noteCount: number; sizeBytes: number }
export type IdMigrationFile = { path: string; backupPath: string; id: string; status: IdMigrationFileStatus }
export type IdMigrationFileStatus = "pending" | "backupCreated" | "applied" | "rolledBack"
export type IdMigrationRecovery = { journalPath: string; backupPath: string; status: IdMigrationStatus; files: IdMigrationFile[] }
export type IdMigrationRecoveryAction = "resume" | "rollback" | "inspectOnly"
export type IdMigrationResult = { backupPath: string; journalPath: string; modifiedPaths: string[]; status: IdMigrationStatus }
export type IdMigrationStatus = "planned" | "inProgress" | "completed" | "rolledBack"
export type ImportedAsset = { relPath: string; absPath: string; fileName: string; kind: string }
/**
 * Health of the rebuildable SQLite index. Markdown files remain authoritative
 * regardless of this state.
 */
export type IndexState = "healthy" | "degraded" | "rebuildRequired"
export type IndexedNote = { id: string; path: string; title: string; modified: number | null; wordCount: number }
export type LayerResult = { notePath: string; layerPath: string; kind: string; pathChanges: PathChange[] }
export type LinkGraph = { nodes: LinkGraphNode[]; edges: LinkGraphEdge[] }
export type LinkGraphEdge = { source: string; target: string; label: string; unresolved?: boolean | null }
export type LinkGraphNode = { id: string; label: string; unresolved?: boolean | null }
export type LoadVaultResult = { generation: number; vaultPath: string; tree: TreeItem[]; notes: IndexedNote[]; sync: SyncReport }
/**
 * The filesystem result is authoritative. A cache failure is returned as a
 * recoverable warning rather than turning a completed mutation into an error.
 */
export type MutationOutcome = { mutation: FsMutationResult; indexState: IndexState; warnings: OperationWarning[] }
export type NoteLayers = { canvas: boolean; sketch: boolean; database: boolean }
export type NoteMetadata = { created: number | null; modified: number | null; wordCount: number }
export type NoteProperties = { hasFrontmatter: boolean; frontmatterStatus: FrontmatterStatus; bodyReadOnly: boolean; properties: FrontmatterProperty[]; parseError: string | null; customProperties: CustomProperty[] }
/**
 * Editor text, its on-disk revision, and the complete source retained as a
 * restore template. Revisions hash unnormalised body bytes for stable IDs and
 * the complete source for opaque path keys, detecting YAML-only external edits.
 * Unterminated frontmatter is edited as full source; other notes expose body.
 */
export type NoteReadOutcome = { content: string; revision: string; source: string }
export type OperationWarning = "indexRebuildRequired"
export type PathChange = { oldPath: string; newPath: string }
export type RecoveryEntry = { version: number; vaultGeneration: number; documentKind: string; id: string; pathHint: string; savedAtMs: number; content: string; contentHash: string }
export type RefactorPreview = { notes: number; replacements: number }
export type RestoreDeletedNoteRequest = { expectedGeneration: number; noteId: string; path: string; content: string; sourceTemplate: string; originWindow: string }
export type SearchResult = { note: IndexedNote; matchType: string; snippet: string | null; score: number }
export type SnapshotEntry = { id: string; createdAtMs: number; reason: string; sizeBytes: number }
export type SnapshotText = { sourcePath: string; content: string }
export type SyncReport = { inserted: number; updated: number; deleted: number; warnings: string[]; pathToId: Partial<{ [key in string]: string }> }
export type TagEntry = { tag: string; notes: IndexedNote[] }
export type TrashEntry = { id: string; originalPath: string; deletedAtMs: number; name: string }
export type TreeItem = { id: string; path: string; name: string; type: string; icon: string; created?: number | null; modified?: number | null; children?: TreeItem[] | null }
export type VaultPreflight = { notes: number; attachments: number; malformedFrontmatter: string[]; userManagedIds: string[]; duplicateIds: string[]; plannedIdWrites: string[]; unfinishedMigrations: IdMigrationRecovery[] }
/**
 * A save failure that callers can distinguish from transport and filesystem
 * failures. In particular, a stale renderer must never retry a CAS conflict
 * with its old buffer.
 */
export type WriteNoteError = { kind: "revisionConflict"; actual_revision: string } | { kind: "failed"; message: string }
export type WriteNoteOutcome = { path: string; revision: string; indexState: IndexState; warnings: OperationWarning[] }
export type WriteNoteRequest = { expectedGeneration: number; noteId: string; content: string; expectedRevision: string; originWindow: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
